services:
  app:
    build: .
    container_name: socialmedia_app
    expose:
      - "5000"
    env_file:
      - .env
    networks:
      - shared-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  shared-net:
    external: true
